### ISSUE TITLE
qreader does not focus

### ISSUE THREAD

**Issue by LeoUnglaub** [nisrulz/qreader#1]
Hey,
i have implemented your library into a small project of mine. The problem i am facing is that the camera does not focus automatically and therefor i never get a scan result. Any ideas on how i can fix that?

Thanks and greetings
Leo
![13054629_1075658902501699_2024864934_o](https://cloud.githubusercontent.com/assets/734684/14778491/7f0a4f2a-0ad3-11e6-9af4-9c36f7901ead.png)

**Comment by nisrulz** [comment]
@LeoUnglaub thats a really good catch. 
I will give an option to enable autofocus in my library.

Should update my code tonight 😄

**Comment by LeoUnglaub** [comment]
Thats awesome!
Big thanks and greetings from Vienna!

Leo

**Comment by nisrulz** [comment]
@LeoUnglaub it was a quick fix, so I updated my code. Have pushed the new version to maven central, should be available in a few hours.
The new version is `1.0.1`

**Comment by LeoUnglaub** [comment]
Hey,
thanks for fixing that issue. But sadly i still cannot scan anything on my phone. I use your code from the readme. I gave the app permissions to use the camera but i still dont get the value from the library. Is there anything else i have to do? installing the Google vision library on my phone? Or something else?

Thanks and greetings
Leo

**Comment by LeoUnglaub** [comment]
I think i might found the problem:
```
Exception thrown from receiver.
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
 at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6566)
 at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:946)
 at android.view.ViewGroup.invalidateChild(ViewGroup.java:5081)
 at android.view.View.invalidateInternal(View.java:12723)
 at android.view.View.invalidate(View.java:12659)
 at android.widget.TextView.invalidateRegion(TextView.java:5185)
 at android.widget.TextView.invalidateCursor(TextView.java:5128)
 at android.widget.TextView.spanChange(TextView.java:8085)
 at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:10181)
 at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:1053)
 at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:759)
 at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
 at android.text.Selection.setSelection(Selection.java:76)
 at android.text.Selection.setSelection(Selection.java:87)
 at android.text.method.ArrowKeyMovementMethod.initialize(ArrowKeyMovementMethod.java:325)
 at android.widget.TextView.setText(TextView.java:4335)
 at android.widget.TextView.setText(TextView.java:4204)
 at android.widget.EditText.setText(EditText.java:84)
 at android.widget.TextView.setText(TextView.java:4179)
 at com.example.simpletest.simpletest.MainActivity$1.onDetected(MainActivity.java:35)
 at github.nisrulz.qreader.QREader$2.receiveDetections(QREader.java:115)
 at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
 at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
 at java.lang.Thread.run(Thread.java:818)
```

**Comment by nisrulz** [comment]
@LeoUnglaub yes the result returned is on a different thread. You need to `post` the data. Check the sample app in the repo.
