### ISSUE TITLE
Error building with proguard

### ISSUE THREAD

**Issue by datnt1987** [nisrulz/qreader#47]
I have build my project with proguard using QReader Libs but it throw error "can't find common super class ...LatLngBounds (google gms), but when I remove QReader Libs, my project build successfully.
I've tried to add into proguard-rule.pro
-dontwarn github.nisrulz.qreader.**
-keep class github.nisrulz.qreader.** { *; }

But error still appear. Please guide me how to fix this. Thanks

**Comment by nisrulz** [comment]
@datnt1987 can you share the complete error log?

**Comment by datnt1987** [comment]
hi @nisrulz here is my full error log:
Warning:Exception while processing task java.io.IOException: java.lang.IllegalArgumentException: Can't find common super class of [com/google/android/gms/maps/model/LatLngBounds] (with 1 known super classes) and [java/util/Iterator] (with 2 known super classes)

It seem not relate to the Libs, but when I remove "compile libs", It run ok.

**Comment by nisrulz** [comment]
@datnt1987 try adding the below to your proguard file

```
-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**
```

**Comment by datnt1987** [comment]
Dear @nisrulz , I've tried both but nothing has changed. It still occur error.

> -keep public class com.google.android.gms.* { public *; }
> -dontwarn com.google.android.gms.**
I've already insert these before.

**Comment by nisrulz** [comment]
@datnt1987 Let me run this through some tests and then I will get back to you.

**Comment by datnt1987** [comment]
Thanks in advance, expect answering from you, @nisrulz

**Comment by nisrulz** [comment]
@datnt1987 I updated the dependencies today and pushed the code to `develop` branch. When I ran the code with proguard enabled, without any change, the app ran properly.

Could you run the example app on your side with proguard enable from the develop branch. If that works I will release the updated library to jcenter and you can then sync it up for it start working with  your app.

As I see it is some issue with last google play dependency which QREader depends on. 

Let me know if it works.

**Comment by datnt1987** [comment]
Dear @nisrulz , I've tried both branch (master and dev), the app ran properly and I cannot confirm that you changed at dev branch works.

**Comment by nisrulz** [comment]
Ok, can you try using the latest version i have pushed (v `2.1.2`)

use this in your build.gradle

```
compile 'com.github.nisrulz:qreader:2.1.2'
```

**Comment by datnt1987** [comment]
> Warning:Exception while processing task java.io.IOException: java.lang.IllegalArgumentException: > Can't find common super class of [com/google/android/gms/maps/model/LatLngBounds] (with 1 known super classes) and [java/util/Iterator] (with 2 known super classes)

I'm sorry but It's still not work for me with the newest version. :(.

I think that libs using some google service modules and when proguard, qreader libs not keep those classes.
In this case, I found that I cannot access the super class of LatLngBounds is AbstractSafeParcelable (I can access this when not using QREader libs)

This is just my guess.

**Comment by datnt1987** [comment]
In my project, I also use react native lib that have com/airbnb/android/react/maps/AirMapView. When building project by using command line:

> Unexpected error while performing partial evaluation:
>   Class       = [com/airbnb/android/react/maps/AirMapView]
>   Method      = [fitToElements(Z)V]
>   Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [com/google/android/gms/maps/model/LatLngBounds] (with 1 known super classes) and [java/util/Iterator] (with 2 known super classes))

Method detail
```
public void fitToElements(boolean animated) {
        LatLngBounds.Builder builder = new LatLngBounds.Builder();

        boolean addedPosition = false;

        for (AirMapFeature feature : features) {
            if (feature instanceof AirMapMarker) {
                Marker marker = (Marker) feature.getFeature();
                builder.include(marker.getPosition());
                addedPosition = true;
            }
            // TODO(lmr): may want to include shapes / etc.
        }
        if (addedPosition) {
            LatLngBounds bounds = builder.build();
            CameraUpdate cu = CameraUpdateFactory.newLatLngBounds(bounds, baseMapPadding);
            if (map == null) {
                return;
            }
            if (animated) {
                startMonitoringRegion();
                map.animateCamera(cu);
            } else {
                map.moveCamera(cu);
            }
        }
    }
```

So is that have conflicts here ???

**Comment by nisrulz** [comment]
Ok this is interesting. Because QREader doesnot use any google maps dependency.
[Check here](https://github.com/nisrulz/qreader/blob/master/qreader/build.gradle#L40-L41)

This looks more like a conflict, thought I donot have a solution for this. 

I do not have any idea about the react native part of this problem. Probably someone who has worked with react native could chime in. Try posting this on stackoverflow even.

**Comment by datnt1987** [comment]
Yes @nisrulz, I think I should find solution in another way. Thank so much for supporting me like this, I respect that.
