### ISSUE TITLE
java.lang.IllegalStateException: Detector processor must first be set with setProcessor

### ISSUE THREAD

**Issue by Warosaurus** [nisrulz/qreader#8]
Using the sample application at: https://github.com/nisrulz/qreader/tree/master/app

I am receiving an error every few milliseconds while the app is trying to detect a QR code.

The error is:

    E/CameraSource: Exception thrown from receiver.
    java.lang.IllegalStateException: Detector processor must first be set with setProcessor in order to receive detection results.
    at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
    at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:818)

**Comment by nisrulz** [comment]
@Warosaurus Can you provide me more details like device information and more stacktrace to replicate this issue. It works completely fine on all devices and emulators I have tested this on.

**Comment by Warosaurus** [comment]
I've tested it on a Samsung S3 (5.1.1) as well as a OnePlus One (5.1.1) and both give the same error.

```
05-17 10:51:19.103 22744-23054/com.war.qreadertest E/CameraSource: Exception thrown from receiver.
                                                                   java.lang.IllegalStateException: Detector processor must first be set with setProcessor in order to receive detection results.
                                                                       at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
                                                                       at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
                                                                       at java.lang.Thread.run(Thread.java:818)
05-17 10:51:19.116 22744-23054/com.war.qreadertest E/CameraSource: Exception thrown from receiver.
                                                                   java.lang.IllegalStateException: Detector processor must first be set with setProcessor in order to receive detection results.
                                                                       at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
                                                                       at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
                                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by Warosaurus** [comment]
The code taken from your example:

MainActivity.java
```
public class MainActivity extends AppCompatActivity {

	private SurfaceView surfaceView;
	private TextView textView_qrcode_info;
	private Button btn_toggle;
	private boolean isRunning = false;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		surfaceView = (SurfaceView) findViewById(R.id.camera_view);
		textView_qrcode_info = (TextView) findViewById(R.id.code_info);

		QREader.getInstance().setUpConfig(new QRDataListener() {
			@Override public void onDetected(final String data) {
				Log.d("QREader", "Value : " + data);
				textView_qrcode_info.post(new Runnable() {
					@Override public void run() {
						textView_qrcode_info.setText(data);
					}
				});
			}
		});

		QREader.getInstance().init(this, surfaceView);
	}

	@Override protected void onResume() {
		super.onResume();

		QREader.getInstance().start();
		isRunning = true;
	}

	@Override protected void onPause() {
		super.onPause();

		QREader.getInstance().stop();
		isRunning = false;
	}

	@Override protected void onDestroy() {
		super.onDestroy();

		QREader.getInstance().releaseAndCleanup();
		isRunning = false;
	}
}
```

activity_main.xml
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:gravity="center">

	<SurfaceView
		android:id="@+id/camera_view"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:layout_above="@+id/scrollView"/>

	<ScrollView
		android:id="@+id/scrollView"
		android:layout_width="match_parent"
		android:layout_height="200dp"
		android:layout_alignParentBottom="true"
		android:layout_alignParentLeft="true"
		android:layout_alignParentStart="true">

		<TextView
			android:id="@+id/code_info"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:gravity="center"
			android:padding="10dp"
			android:text="Point the camera view to a QR Code to read the information"
			android:textSize="20sp"/>
	</ScrollView>
</RelativeLayout>
```

Android Manifest
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
		  package="com.war.qreadertest">

	<uses-permission android:name="android.permission.CAMERA"/>
...
```

build.gradle
```
...
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.github.nisrulz:qreader:1.0.3'
}
```

**Comment by nisrulz** [comment]
I will test it out.

**Comment by Warosaurus** [comment]
Alright, thanks :)

**Comment by nisrulz** [comment]
fixed in commit a55eea80cdbe6bda2bdbaa44dade935cb9c37b66

**Comment by pin3da** [comment]
I've tested it on a OnePlusOne (6.0.1) using version 1.0.4 of the library and the error persist.

Should I reopen the issue ?

Thanks (:

**Comment by nisrulz** [comment]
You are saying the sample app provided still gives you the same error ? 
I have tested the library code in the latest version. 

Please provide the steps to reproduce the issue. 
Reopening the issue.

**Comment by pin3da** [comment]
I cloned the repository to test, and Android Studio asked me to upgrade the version of Gradle.
After all the updates it worked well.

Then I tested on my app and it also worked.

Sorry for the false alarm ): ... and thank you very much.
